name: riverpod_api
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ">= 1.0.2"
  dio: ">=4.0.6"
  flutter_riverpod: ">=2.1.1"
  freezed_annotation: ">=2.2.0"
  equatable: ">=2.0.5"
  json_annotation: ">=4.7.0"
  # easy_localization: ">=3.0.1"
  flutter_screenutil: ">=5.6.0"
  gap: ">=2.0.1"
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ">=6.5.4"
  build_runner: ">=2.3.2"
  freezed: ">=2.2.1"
  # flutter_gen_runner: ">=5.1.0+1"
  flutter_lints: ">=2.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/
